import base64
import json
import uuid
from pathlib import Path
from datetime import datetime

import pandas as pd
import streamlit as st
import streamlit.components.v1 as components
from streamlit_js_eval import streamlit_js_eval
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

# ----------------------------
# App Identity (edit as needed)
# ----------------------------
APP_NAME = "NeuroAuth™"
COMPANY_NAME = "NeuroAuth Labs"
TAGLINE = "Pre-Authorization Compliance Assistant"
PRIMARY_ICON = "🧠"

BASE_DIR = Path(__file__).resolve().parent


# ----------------------------
# Utilities
# ----------------------------
def load_csv(name: str) -> pd.DataFrame:
    p = BASE_DIR / name
    if not p.exists():
        st.error(f"Missing file: {p}. Run `python setup_neuro_platinum.py` first.")
        st.stop()
    return pd.read_csv(p, encoding="utf-8-sig")


def safe_json_list(x):
    if pd.isna(x):
        return []
    try:
        obj = json.loads(x) if isinstance(x, str) else x
        return obj if isinstance(obj, list) else []
    except Exception:
        return []


def compute_decision(rule, inputs):
    """Return: eligible(bool), risk(0-100), issues(list[str]), missing_critical(list[str])"""
    bypass = len(inputs["redflags_selected"]) > 0
    issues, risk = [], 0

    # Conservative Tx
    if not bypass:
        req_weeks = int(rule["Conservative_Tx_Weeks"])
        req_pt = int(rule["Min_PT_Sessions"])
        if inputs["conservative_weeks"] < req_weeks:
            issues.append(f"Conservative weeks < required ({inputs['conservative_weeks']} < {req_weeks}).")
            risk += 40
        if inputs["pt_sessions"] < req_pt:
            issues.append(f"PT sessions < required ({inputs['pt_sessions']} < {req_pt}).")
            risk += 20
    else:
        # Documentation risk still exists even when bypassing conservative thresholds
        risk += 5

    # Primary evidence
    max_age = int(rule["Imaging_Max_Age_Days"])
    if not inputs["evidence_done"]:
        issues.append("Primary evidence not confirmed.")
        risk += 25
    else:
        if inputs["evidence_age_days"] > max_age:
            issues.append(f"Primary evidence too old ({inputs['evidence_age_days']}d > {max_age}d).")
            risk += 15

    # Attachments
    critical = safe_json_list(rule.get("Critical_Attachments_JSON"))
    missing_critical = [a for a in critical if a not in inputs["attachments_selected"]]
    if missing_critical:
        issues.append("Missing critical attachments: " + ", ".join(missing_critical))
        risk += 35

    # Clamp
    risk = min(100, max(0, risk))

    # Eligibility
    eligible = (
        (len(missing_critical) == 0)
        and inputs["evidence_done"]
        and (inputs["evidence_age_days"] <= max_age)
        and (risk < 35)
    )

    # If bypass: tolerate slightly higher risk (conservative criteria are bypassed)
    if bypass and (len(missing_critical) == 0) and inputs["evidence_done"] and (inputs["evidence_age_days"] <= max_age):
        eligible = (risk < 45)

    return eligible, risk, issues, missing_critical


def export_pdf(lines, out_path: Path):
    c = canvas.Canvas(str(out_path), pagesize=A4)
    width, height = A4

    # Header
    y = height - 72
    c.setFont("Helvetica-Bold", 16)
    c.drawString(72, y, f"{COMPANY_NAME} — {APP_NAME}")
    y -= 18
    c.setFont("Helvetica", 10)
    c.drawString(72, y, TAGLINE)
    y -= 22

    # Body
    c.setFont("Helvetica", 10)
    for line in lines:
        if y < 72:
            c.showPage()
            y = height - 72
            c.setFont("Helvetica", 10)
        c.drawString(72, y, line[:120])
        y -= 14

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(72, 40, "Generated by NeuroAuth™ — For clinical administrative use. Validate payer-specific requirements.")
    c.save()


def pdf_print_widget(pdf_bytes: bytes, filename: str = "evidence_pack.pdf"):
    """Renders a print icon button that opens the PDF in a new tab and triggers browser print."""
    b64 = base64.b64encode(pdf_bytes).decode("utf-8")
    html = f"""
    <div style="display:flex; gap:10px; align-items:center;">
      <a download="{filename}" href="data:application/pdf;base64,{b64}"
         style="text-decoration:none; padding:10px 12px; border-radius:10px; border:1px solid rgba(255,255,255,0.15); display:inline-flex; align-items:center; gap:8px;">
         ⬇️ <span style="font-family:system-ui; font-size:14px;">Download</span>
      </a>
      <button id="printBtn"
        style="cursor:pointer; padding:10px 12px; border-radius:10px; border:1px solid rgba(255,255,255,0.15);
               background:rgba(255,255,255,0.06); color:inherit; display:inline-flex; align-items:center; gap:8px;">
        🖨️ <span style="font-family:system-ui; font-size:14px;">Print</span>
      </button>
    </div>
    <script>
      const b64 = "{b64}";
      document.getElementById("printBtn").onclick = () => {{
        const w = window.open("");
        if (!w) return;
        w.document.write(`
          <html><head><title>{filename}</title></head>
          <body style="margin:0">
            <iframe id="pdf" style="border:0; width:100vw; height:100vh"
              src="data:application/pdf;base64,${{b64}}"></iframe>
            <script>
              const f = document.getElementById('pdf');
              f.onload = () => {{
                try {{ f.contentWindow.focus(); f.contentWindow.print(); }}
                catch(e) {{ window.print(); }}
              }};
            </script>
          </body></html>
        `);
        w.document.close();
      }};
    </script>
    """
    components.html(html, height=70)


# ----------------------------
# Page config + styling
# ----------------------------
st.set_page_config(
    page_title=f"{APP_NAME} — Neuro",
    page_icon=PRIMARY_ICON,
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown(
    """
<style>
/* Hide Streamlit chrome */
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}
header {visibility: hidden;}

/* App typography */
html, body, [class*="css"]  {
  font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;
}

/* Card-like containers */
.card {
  background: rgba(255,255,255,0.04);
  border: 1px solid rgba(255,255,255,0.10);
  border-radius: 18px;
  padding: 16px 16px;
}

.small-muted { color: rgba(255,255,255,0.70); font-size: 12px; }
.badge {
  display:inline-block; padding:4px 10px; border-radius:999px;
  border:1px solid rgba(255,255,255,0.15);
  background: rgba(255,255,255,0.04);
  font-size: 12px;
}

/* Responsive spacing */
.block-container { padding-top: 1.5rem; padding-bottom: 2rem; }

@media (max-width: 768px) {
  .block-container { padding-left: 0.8rem; padding-right: 0.8rem; }
  .card { padding: 12px; border-radius: 14px; }
  .small-muted { font-size: 11px; }
  .badge { font-size: 11px; padding: 4px 9px; }
}

@media (max-width: 420px) {
  .block-container { padding-left: 0.6rem; padding-right: 0.6rem; }
  .card { padding: 10px; }
}
</style>
""",
    unsafe_allow_html=True,
)


# ----------------------------
# Session
# ----------------------------
if "sid" not in st.session_state:
    st.session_state["sid"] = str(uuid.uuid4())

if "latest_pdf_bytes" not in st.session_state:
    st.session_state["latest_pdf_bytes"] = None
    st.session_state["latest_pdf_name"] = None
    width = streamlit_js_eval(js_expressions="window.innerWidth", key="WIN_WIDTH")
is_mobile = False
try:
    is_mobile = (width is not None) and (int(width) < 768)
except Exception:
    is_mobile = False

st.session_state["latest_summary"] = None


# ----------------------------
# Sidebar: Data + selections
# ----------------------------
with st.sidebar:
    st.markdown(f"## {PRIMARY_ICON} {APP_NAME}")
    st.markdown(f"<div class='small-muted'>{COMPANY_NAME}<br>{TAGLINE}</div>", unsafe_allow_html=True)
    st.markdown("---")

    proc_df = load_csv("procedures.csv")
    dx_df = load_csv("diagnoses.csv")
    rules_df = load_csv("rules_advanced.csv")

    proc_df["Label"] = proc_df["CPT"].astype(str) + " — " + proc_df["Name_EN"].astype(str)
    selected_label = st.selectbox("Procedure (CPT)", proc_df["Label"].tolist())
    selected_cpt = selected_label.split("—")[0].strip()

    rule_row = rules_df[rules_df["CPT_Code"].astype(str) == str(selected_cpt)]
    if rule_row.empty:
        st.error(f"No rule found for CPT {selected_cpt}. Run setup script again.")
        st.stop()
    rule = rule_row.iloc[0].to_dict()

    st.markdown(
        f"<div class='badge'>Rule: {rule.get('Rule_Version','n/a')}</div>",
        unsafe_allow_html=True
    )
    st.markdown(
        f"<div class='small-muted'>Evidence: <b>{rule.get('Required_Imaging','Evidence')}</b> "
        f"(≤ {int(rule['Imaging_Max_Age_Days'])} days)</div>",
        unsafe_allow_html=True
    )
    st.markdown("---")

    show_debug = st.checkbox("Show debug panel", value=False)

# ----------------------------
# Top bar
# ----------------------------
top_l, top_r = st.columns([3, 2])
with top_l:
    st.markdown(f"### {PRIMARY_ICON} {APP_NAME}")
    st.markdown(f"<div class='small-muted'>{TAGLINE} — Neurosurgery Knowledge Base</div>", unsafe_allow_html=True)
with top_r:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    st.markdown(
        f"<div style='text-align:right' class='small-muted'>"
        f"{COMPANY_NAME}<br>Session: {st.session_state['sid'][:8]} • {now}"
        f"</div>",
        unsafe_allow_html=True
    )

if show_debug:
    with st.expander("Debug (paths & data)"):
        st.write(f"BASE_DIR: `{BASE_DIR}`")
        st.write("procedures.csv rows:", len(proc_df))
        st.write("rules_advanced.csv rows:", len(rules_df))


# ----------------------------
# Main: Tabs
# ----------------------------
tab_assess, tab_report, tab_about = st.tabs(["Assessment", "Evidence Pack", "About"])

with tab_assess:
    st.markdown("<div class='card'>", unsafe_allow_html=True)

    # Diagnosis filtering
    allowed_icd = safe_json_list(rule.get("Allowed_ICD_JSON"))
    dx_view = dx_df[dx_df["ICD_Code"].isin(allowed_icd)].copy() if allowed_icd else dx_df.copy()
    dx_view["DxLabel"] = dx_view["ICD_Code"] + " — " + dx_view["Description"]
    selected_dx = st.selectbox("Diagnosis (ICD)", dx_view["DxLabel"].tolist())

    criteria = safe_json_list(rule.get("Criteria_Symptoms_JSON"))
    redflags = safe_json_list(rule.get("RedFlag_Exceptions_JSON"))

    if is_mobile:
        st.subheader("Clinical criteria")
        if not criteria:
            st.caption("No structured criteria for this procedure.")
        crit_selected = [x for x in criteria if st.checkbox(x, key=f"crit_{selected_cpt}_{x}")]

        st.subheader("Red flags (bypass)")
        if not redflags:
            st.caption("No red-flag bypass rules defined.")
        red_selected = [x for x in redflags if st.checkbox(x, key=f"rf_{selected_cpt}_{x}")]

        st.subheader("Primary evidence")
        st.caption(f"Type: {rule.get('Required_Imaging','Evidence')}")
        evidence_done = st.checkbox("Evidence available / attached", value=True)
        evidence_age_days = st.number_input("Evidence age (days)", min_value=0, max_value=3650, value=30, step=1)
    else:
        c1, c2, c3 = st.columns([1.3, 1.1, 1.1])

        with c1:
            st.subheader("Clinical criteria")
            if not criteria:
                st.caption("No structured criteria for this procedure.")
            crit_selected = [x for x in criteria if st.checkbox(x, key=f"crit_{selected_cpt}_{x}")]

        with c2:
            st.subheader("Red flags (bypass)")
            if not redflags:
                st.caption("No red-flag bypass rules defined.")
            red_selected = [x for x in redflags if st.checkbox(x, key=f"rf_{selected_cpt}_{x}")]

        with c3:
            st.subheader("Primary evidence")
            st.caption(f"Type: {rule.get('Required_Imaging','Evidence')}")
            evidence_done = st.checkbox("Evidence available / attached", value=True)
            evidence_age_days = st.number_input("Evidence age (days)", min_value=0, max_value=3650, value=30, step=1)

    st.divider()

    l1, l2 = st.columns([1.1, 1.2])

    with l1:
        st.subheader("Conservative management")
        req_weeks = int(rule["Conservative_Tx_Weeks"])
        req_pt = int(rule["Min_PT_Sessions"])
        st.caption(f"Required if no bypass: {req_weeks} weeks • {req_pt} PT sessions")

        conservative_weeks = st.number_input("Weeks completed", min_value=0, max_value=260, value=req_weeks, step=1)
        pt_sessions = st.number_input("PT sessions completed", min_value=0, max_value=200, value=req_pt, step=1)

    with l2:
        st.subheader("Attachments")
        critical = safe_json_list(rule.get("Critical_Attachments_JSON"))
        supportive = safe_json_list(rule.get("Supportive_Attachments_JSON"))
        all_atts = list(dict.fromkeys(critical + supportive))
        if not all_atts:
            st.caption("No attachments defined in rules.")
        attachments_selected = st.multiselect("Select attachments available", all_atts, default=critical)

    inputs = {
        "redflags_selected": red_selected,
        "evidence_done": evidence_done,
        "evidence_age_days": int(evidence_age_days),
        "conservative_weeks": int(conservative_weeks),
        "pt_sessions": int(pt_sessions),
        "attachments_selected": attachments_selected,
    }

    eligible, risk, issues, missing_critical = compute_decision(rule, inputs)

    st.divider()
    s1, s2, s3 = st.columns([1.2, 0.8, 1.0])

    with s1:
        if eligible:
            st.success("Status: Eligible (Low/Moderate risk)")
        else:
            st.error("Status: Needs Review (High risk / missing evidence)")
        if issues:
            st.markdown("**Issues:**")
            for it in issues:
                st.write("• " + it)

    with s2:
        st.metric("Risk Score", f"{risk}/100")
        st.progress(risk / 100)

    with s3:
        st.markdown("**Quick summary**")
        st.write(f"- Procedure: {selected_label}")
        st.write(f"- Diagnosis: {selected_dx}")
        st.write(f"- Bypass selected: {'Yes' if len(red_selected)>0 else 'No'}")
        st.write(f"- Evidence OK: {'Yes' if evidence_done and int(evidence_age_days) <= int(rule['Imaging_Max_Age_Days']) else 'No'}")
        st.write(f"- Missing critical: {', '.join(missing_critical) if missing_critical else '-'}")

    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown("")

    gen_col1, gen_col2 = st.columns([1, 3])
    with gen_col1:
        generate = st.button("Generate Evidence Pack", type="primary", use_container_width=True)
    with gen_col2:
        st.caption("Generates a summary + PDF in the Evidence Pack tab. This is not a claim submission (NPHIES not integrated).")

    if generate:
        tx_id = str(uuid.uuid4())
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        lines = [
            f"Transaction ID: {tx_id}",
            f"Timestamp: {ts}",
            f"CPT: {selected_label}",
            f"Diagnosis: {selected_dx}",
            f"Rule Version: {rule.get('Rule_Version','n/a')}",
            f"Decision: {'Eligible' if eligible else 'Needs Review'} | Risk={risk}",
            f"Clinical criteria: {', '.join(crit_selected) if crit_selected else '-'}",
            f"Red flags: {', '.join(red_selected) if red_selected else '-'}",
            f"Primary evidence: {rule.get('Required_Imaging','Evidence')} | Done={evidence_done} | AgeDays={int(evidence_age_days)}",
            f"Conservative management: {int(conservative_weeks)} weeks | PT sessions: {int(pt_sessions)}",
            f"Attachments: {', '.join(attachments_selected) if attachments_selected else '-'}",
        ]
        if missing_critical:
            lines.append("Missing critical attachments: " + ", ".join(missing_critical))

        out_dir = BASE_DIR / "output"
        out_dir.mkdir(exist_ok=True)
        pdf_name = f"evidence_pack_{tx_id}.pdf"
        pdf_path = out_dir / pdf_name
        export_pdf(lines, pdf_path)

        pdf_bytes = pdf_path.read_bytes()

        st.session_state["latest_pdf_bytes"] = pdf_bytes
        st.session_state["latest_pdf_name"] = pdf_name
        st.session_state["latest_summary"] = "\n".join(lines)

        st.success("Evidence Pack generated. Open the Evidence Pack tab to download/print.")

with tab_report:
    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.subheader("Evidence Pack")
    if st.session_state["latest_summary"] is None:
        st.info("No Evidence Pack generated yet. Go to the Assessment tab and click **Generate Evidence Pack**.")
    else:
        st.text_area("Summary (copy/paste)", value=st.session_state["latest_summary"], height=260)
        st.markdown("#### Actions")
        pdf_bytes = st.session_state["latest_pdf_bytes"]
        pdf_name = st.session_state["latest_pdf_name"] or "evidence_pack.pdf"
        if is_mobile:
            st.download_button("⬇️ Download PDF", data=pdf_bytes, file_name=pdf_name, mime="application/pdf", use_container_width=True)
        else:
            pdf_print_widget(pdf_bytes, filename=pdf_name)
            st.caption("Tip: Print uses your browser print dialog. If your browser blocks popups, allow popups for localhost.")
    st.markdown("</div>", unsafe_allow_html=True)

with tab_about:
    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.subheader("About")
    st.write(
        "This MVP is a **pre-authorization compliance assistant**: it checks internal clinical criteria, "
        "evidence freshness, and attachment completeness. It does **not** submit claims or integrate with NPHIES."
    )
    st.write("Developed By Khalid Ajmi")
st.markdown("</div>", unsafe_allow_html=True)
